services:
  api:
    image: "ghcr.io/simsustech/slimfact:latest"
    labels:
      caddy: ${HOST}
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      - ./jwks/:/app/dist/server/jwks/
    environment:
      # Modular API
      VITE_API_HOST: ${HOST}
      OIDC_ISSUER_NAME: ${OIDC_ISSUER_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      LICENSE_KEY: ${LICENSE_KEY}
      OIDC_COOKIES_KEYS: /run/secrets/OIDC_COOKIES_KEYS
      OTP_SECRET_FILE: /run/secrets/OTP_SECRET
      OTP_VALIDITY_SECONDS: 3600
      EMAIL_FOOTER: "Footer"
      VITE_TITLE: SlimFact dev
      VITE_LANG: en-US
      # VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}

    # entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    secrets:
      - POSTGRES_PASSWORD
      - OTP_SECRET
      - OIDC_COOKIES_KEYS
    networks:
      web:
      slimfact:
        aliases:
          - api
    restart: unless-stopped

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    networks:
      slimfact:
        aliases:
          - database
    restart: unless-stopped

secrets:
  POSTGRES_PASSWORD:
    file: ./env/POSTGRES_PASSWORD
  OTP_SECRET:
    file: ./env/OTP_SECRET
  OIDC_COOKIES_KEYS:
    file: ./env/OIDC_COOKIES_KEYS

networks:
  slimfact:
  web:
    external: true
