injectWorkspacePackages: true

packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - "@simsustech/quasar-components"
  - vue-router
  - "@modular-api/*"
  - vue
  - "@vue/*"
  - oidc-provider
  - typescript-eslint
  - "@typescript-eslint/*"
  - vite
  - oxfmt
  - "@oxfmt/*"
  - oxlint
  - "@oxlint/*"
  - fast-xml-parser
  - playwright
  - playwright-core
  - "@playwright/*"
  - "@types/node"
  - content-type
  - vitest
  - "@vitest/*"
  - kysely

allowBuilds:
  "@parcel/watcher": true
  ejs: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
