packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - "@simsustech/quasar-components"
  - vue-router
  - "@modular-api/*"
  - fast-xml-parser
  - fast-xml-builder
  - cronstrue
  - pg*
  - unocss
  - "@unocss/*"
  - "@types/node"
