injectWorkspacePackages: true

packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - browserslist
  - '@modular-api/fastify-checkout@0.9.0'
  - '@types/pg@8.20.4'
  - '@vue/compiler-core@3.5.41'
  - '@vue/compiler-dom@3.5.41'
  - '@vue/compiler-sfc@3.5.41'
  - '@vue/compiler-ssr@3.5.41'
  - '@vue/reactivity@3.5.41'
  - '@vue/runtime-core@3.5.41'
  - '@vue/runtime-dom@3.5.41'
  - '@vue/server-renderer@3.5.41'
  - '@vue/shared@3.5.41'
  - quasar@2.24.0
  - vue@3.5.41
  - unocss-preset-quasar@0.5.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - ejs
  - esbuild
  - sharp
  - simple-git-hooks

minimumReleaseAgeIgnoreMissingTime: true

allowBuilds:
  "@parcel/watcher": true
  ejs: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
