injectWorkspacePackages: true

packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - "@simsustech/quasar-components"
  - "@modular-api/*"
  - "@quasar/*"
  - vue-router
  - unocss-preset-quasar
  - oxfmt
  - "@oxfmt/*"
  - "@myriaddreamin/*"
  - "@oxlint/*"
  - oxlint
  - vite

allowBuilds:
  "@parcel/watcher": true
  ejs: true
  esbuild: true
  sharp: true
  simple-git-hooks: true

minimumReleaseAgeIgnoreMissingTime: true
