packages:
  - packages/*

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@vitrify/*"
  - vitrify
  - "@simsustech/quasar-components"
  - vue-router
  - "@modular-api/api"
  - "@modular-api/fastify-checkout"
