#let nl = (
  invoice: (
    title: "Factuur",
    concept: "Concept",
    fields: (
      quantity: "Aantal",
      amount: "Bedrag",
      description: "Omschrijving",
      listPrice: "Prijs per stuk",
      vat: "BTW",
      discount: "Korting",
      totalExcludingTax: "Totaal excl. btw",
      totalIncludingTax: "Totaal incl. btw",
      invoiceNumber: "Factuurnummer",
      invoiceDate: "Factuurdatum",
      cocNumber: "KvK nummer",
      iban: "IBAN",
      bic: "BIC",
      vatIdNumber: "BTW ID",
      listPriceIncludesTax: "Prijzen incl. btw",
      quantityPerMille: "Aantal per duizend",
      quantityUnit: "Eenheid",
    ),
    status: (
      concept: "Concept",
      open: "Open",
      paid: "Betaald",
      receipt: "Bon",
      bill: "Rekening",
      canceled: "Geannuleerd",
    ),
    footer: (
      paymentTermDays,
      companyName,
      dueDate,
      iban,
    ) => text[Te betalen binnen #paymentTermDays dagen (voor *#dueDate*) op rekeningnummer *#iban* t.n.v. *#companyName* onder vermelding van factuurnummer.],
    labels: (
      amountIncludingTax: "Bedrag incl. btw",
      amountExcludingTax: "Bedrag excl. btw",
      inclusive: "incl.",
      exclusive: "excl.",
    ),
  ),
  countries: (
    SA: "Saudi-Arabië",
    BD: "Bangladesh",
    IN: "India",
    CZ: "Tsjechië",
    DK: "Denemarken",
    AT: "Oostenrijk",
    CH: "Zwitserland",
    DE: "Duitsland",
    GR: "Griekenland",
    AU: "Australië",
    CA: "Canada",
    GB: "Verenigd Koninkrijk",
    IE: "Ierland",
    NZ: "Nieuw-Zeeland",
    US: "Verenigde Staten",
    ZA: "Zuid-Afrika",
    AR: "Argentinië",
    CL: "Chili",
    CO: "Colombia",
    ES: "Spanje",
    MX: "Mexico",
    FI: "Finland",
    BE: "België",
    FR: "Frankrijk",
    IL: "Israël",
    HU: "Hongarije",
    ID: "Indonesië",
    IT: "Italië",
    JP: "Japan",
    KR: "Zuid-Korea",
    NL: "Nederland",
    NO: "Noorwegen",
    PL: "Polen",
    BR: "Brazilië",
    PT: "Portugal",
    RO: "Roemenië",
    RU: "Rusland",
    SK: "Slowakije",
    SE: "Zweden",
    LK: "Sri Lanka",
    TH: "Thailand",
    TR: "Turkije",
    CN: "China",
    HK: "Hongkong",
    TW: "Taiwan",
  ),
)

#let de = (
    invoice: (
      title: "Rechnung",
      concept: "Konzept",
      fields: (
        quantity: "Menge",
        amount: "Betrag",
        description: "Beschreibung",
        listPrice: "Einzelpreis",
        vat: "MwSt.",
        discount: "Rabatt",
        totalExcludingTax: "Gesamt Netto",
        totalIncludingTax: "Gesamt Brutto",
        invoiceNumber: "Rechnungsnummer",
        invoiceDate: "Rechnungsdatum",
        cocNumber: "Handelsregisternummer",
        iban: "IBAN",
        bic: "BIC",
        vatIdNumber: "USt-IdNr.",
        listPriceIncludesTax: "Preise inkl. MwSt.",
        quantityPerMille: "Menge pro Mille",
        quantityUnit: "Einheit",
      ),
      status: (
        concept: "Entwurf",
        open: "Offen",
        paid: "Bezahlt",
        receipt: "Quittung",
        bill: "Beleg",
        canceled: "Storniert",
      ),
      footer: (
        paymentTermDays,
        companyName,
        dueDate,
        iban,
      ) => text[Zahlbar innerhalb von *#paymentTermDays* Tagen (bis zum *#dueDate*) auf das Bankkonto mit der IBAN *#iban* lautend auf *#companyName*.
        Bitte geben Sie bei der Überweisung Ihre Rechnungsnummer an.],
      labels: (
        amountIncludingTax: "Betrag inkl. MwSt.",
        amountExcludingTax: "Betrag exkl. MwSt.",
        inclusive: "inkl.",
        exclusive: "exkl.",
      ),
    ),
    countries: (
      SA: "Saudi-Arabien",
      BD: "Bangladesch",
      IN: "Indien",
      CZ: "Tschechische Republik",
      DK: "Dänemark",
      AT: "Österreich",
      CH: "Schweiz",
      DE: "Deutschland",
      GR: "Griechenland",
      AU: "Australien",
      CA: "Kanada",
      GB: "Vereinigtes Königreich",
      IE: "Irland",
      NZ: "Neuseeland",
      US: "Vereinigte Staaten",
      ZA: "Südafrika",
      AR: "Argentinien",
      CL: "Chile",
      CO: "Kolumbien",
      ES: "Spanien",
      MX: "Mexiko",
      FI: "Finnland",
      BE: "Belgien",
      FR: "Frankreich",
      IL: "Israel",
      HU: "Ungarn",
      ID: "Indonesien",
      IT: "Italien",
      JP: "Japan",
      KR: "Republik Korea",
      NL: "Niederlande",
      NO: "Norwegen",
      PL: "Polen",
      BR: "Brasilien",
      PT: "Portugal",
      RO: "Rumänien",
      RU: "Russische Föderation",
      SK: "Slowakei",
      SE: "Schweden",
      LK: "Sri Lanka",
      TH: "Thailand",
      TR: "Türkei",
      CN: "China",
      HK: "Hongkong",
      TW: "Taiwan",
    ),
)

#let translations = (
  "nl-NL": nl,
  "nl": nl,
  "de": de,
  "de-DE": de,
  "en-US": (
    invoice: (
      title: "Invoice",
      concept: "Concept",
      fields: (
        quantity: "Quantity",
        amount: "Amount",
        description: "Description",
        listPrice: "Unit price",
        vat: "VAT",
        discount: "Discount",
        totalExcludingTax: "Total excl. tax",
        totalIncludingTax: "Total incl. tax",
        invoiceNumber: "Invoice number",
        invoiceDate: "Invoice date",
        cocNumber: "CoC number",
        iban: "IBAN",
        bic: "BIC",
        vatIdNumber: "VAT ID",
        listPriceIncludesTax: "Prices incl. VAT",
        quantityPerMille: "Quantity per mille",
        quantityUnit: "Unit",
      ),
      status: (
        concept: "Concept",
        open: "Open",
        paid: "Paid",
        receipt: "Receipt",
        bill: "Bill",
        canceled: "Canceled",
      ),
      footer: (
        paymentTermDays,
        companyName,
        dueDate,
        iban,
      ) => text[Payment to be received within *#paymentTermDays* days (before *#dueDate*) on bank account number *#iban* in the name of *#companyName*.
        Please include your invoice number on the bank transaction.],
      labels: (
        amountIncludingTax: "Amount incl. tax",
        amountExcludingTax: "Amount excl. tax",
        inclusive: "incl.",
        exclusive: "excl.",
      ),
    ),
    countries: (
      SA: "Saudi Arabia",
      BD: "Bangladesh",
      IN: "India",
      CZ: "Czech Republic",
      DK: "Denmark",
      AT: "Austria",
      CH: "Switzerland",
      DE: "Germany",
      GR: "Greece",
      AU: "Australia",
      CA: "Canada",
      GB: "United Kingdom",
      IE: "Ireland",
      NZ: "New Zealand",
      US: "United States",
      ZA: "South Africa",
      AR: "Argentina",
      CL: "Chile",
      CO: "Colombia",
      ES: "Spain",
      MX: "Mexico",
      FI: "Finland",
      BE: "Belgium",
      FR: "France",
      IL: "Israel",
      HU: "Hungarian",
      ID: "Indonesia",
      IT: "Italy",
      JP: "Japan",
      KR: "Republic of Korea",
      NL: "The Netherlands",
      NO: "Norway",
      PL: "Polish",
      BR: "Brazil",
      PT: "Portugal",
      RO: "Romania",
      RU: "Russian Federation",
      SK: "Slovakia",
      SE: "Sweden",
      LK: "Sri Lanka",
      TH: "Thai",
      TR: "Turkey",
      CN: "China",
      HK: "Hong Kong",
      TW: "Taiwan",
    ),
  ),
)
