#let translations = (
  "nl": (
    invoice: (
      title: "Factuur",
      concept: "Concept",
      fields: (
        quantity: "Aantal",
        amount: "Bedrag",
        description: "Omschrijving",
        listPrice: "Prijs per stuk",
        vat: "BTW",
        discount: "Korting",
        totalExcludingTax: "Totaal excl. btw",
        totalIncludingTax: "Totaal incl. btw",
        invoiceNumber: "Factuurnummer",
        invoiceDate: "Factuurdatum",
        cocNumber: "KvK nummer",
        iban: "IBAN",
        bic: "BIC",
        vatIdNumber: "BTW ID",
        listPriceIncludesTax: "Prijzen incl. btw",
        quantityPerMille: "Aantal per duizend",
        quantityUnit: "Eenheid",
      ),
      status: (
        concept: "Concept",
        open: "Open",
        paid: "Betaald",
        receipt: "Bon",
        bill: "Rekening",
        canceled: "Geannuleerd",
      ),
      footer: (
        paymentTermDays,
        companyName,
        dueDate,
        iban,
      ) => text[Te betalen binnen #paymentTermDays dagen (voor *#dueDate*) op rekeningnummer *#iban* t.n.v. *#companyName* onder vermelding van factuurnummer.],
      labels: (
        amountIncludingTax: "Bedrag incl. btw",
        amountExcludingTax: "Bedrag excl. btw",
        inclusive: "incl.",
        exclusive: "excl.",
      ),
    ),
  ),
  "en-US": (
    invoice: (
      title: "Invoice",
      concept: "Concept",
      fields: (
        quantity: "Quantity",
        amount: "Amount",
        description: "Description",
        listPrice: "Unit price",
        vat: "VAT",
        discount: "Discount",
        totalExcludingTax: "Total excl. tax",
        totalIncludingTax: "Total incl. tax",
        invoiceNumber: "Invoice number",
        invoiceDate: "Invoice date",
        cocNumber: "CoC number",
        iban: "IBAN",
        bic: "BIC",
        vatIdNumber: "VAT ID",
        listPriceIncludesTax: "Prices incl. VAT",
        quantityPerMille: "Quantity per mille",
        quantityUnit: "Unit",
      ),
      status: (
        concept: "Concept",
        open: "Open",
        paid: "Paid",
        receipt: "Receipt",
        bill: "Bill",
        canceled: "Canceled",
      ),
      footer: (
        paymentTermDays,
        companyName,
        dueDate,
        iban,
      ) => text[Payment to be received within *#paymentTermDays* days (before *#dueDate*) on bank account number *#iban* in the name of *#companyName*.
        Please include your invoice number on the bank transaction.],
      labels: (
        amountIncludingTax: "Amount incl. tax",
        amountExcludingTax: "Amount excl. tax",
        inclusive: "incl.",
        exclusive: "excl.",
      ),
    ),
  ),
)
