// GENERATED by packages/tools/scripts/generate-demo-data.mjs — do not edit.
// Synthetic demo data for the api seed:demo; regenerate with `pnpm --filter @slimfact/tools generate:demo`.
export const demoCore = {
  companies: [
    {
      name: 'Bouwhuis & Partners BV',
      address: 'Kanaaldijk 12',
      postalCode: '1011 AB',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@bouwhuis.example',
      cocNumber: '12345678',
      prefix: 'bouwhuis',
      vatIdNumber: 'NL123456789B01',
      emailBcc: null,
      iban: 'NL60KNAB3169130445',
      bic: 'KNABNL2H'
    },
    {
      name: 'Noordzee Techniek BV',
      address: 'Havenstraat 4',
      postalCode: '2011 AC',
      city: 'Haarlem',
      country: 'NL',
      email: 'info@noordzee.example',
      cocNumber: '23456789',
      prefix: 'noordzee',
      vatIdNumber: 'NL234567890B02',
      emailBcc: null,
      iban: 'NL65RABO5383122816',
      bic: 'RABONL2U'
    },
    {
      name: 'Hollandia Dakwerken BV',
      address: 'Dijkweg 8',
      postalCode: '3011 AD',
      city: 'Rotterdam',
      country: 'NL',
      email: 'info@hollandia.example',
      cocNumber: '34567890',
      prefix: 'hollandia',
      vatIdNumber: 'NL345678901B03',
      emailBcc: null,
      iban: 'NL73SNSB9788852396',
      bic: 'SNSBNL2A'
    }
  ],
  clients: [
    {
      companyName: 'De Vries Hoveniers',
      address: 'Tuinlaan 3',
      postalCode: '1012 AE',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@devries.example',
      contactPersonName: 'Jan de Vries'
    },
    {
      companyName: 'Van Dijk Elektra',
      address: 'Stroomweg 7',
      postalCode: '1013 AF',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@vandijk.example',
      contactPersonName: 'Piet van Dijk'
    },
    {
      companyName: 'Bakker & Zonen',
      address: 'Bakkerstraat 9',
      postalCode: '1014 AG',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@bakker.example',
      contactPersonName: 'Kees Bakker'
    },
    {
      companyName: 'Jansen Tuinbouw',
      address: 'Kaslaan 11',
      postalCode: '1015 AH',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@jansen.example',
      contactPersonName: 'Marijke Jansen'
    },
    {
      companyName: 'Smit Bouwservice',
      address: 'Bouwstraat 15',
      postalCode: '1016 AJ',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@smit.example',
      contactPersonName: 'Henk Smit'
    },
    {
      companyName: 'Mulder Interieur',
      address: 'Meubelhof 2',
      postalCode: '1017 AK',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@mulder.example',
      contactPersonName: 'Els Mulder'
    },
    {
      companyName: 'Visser Loodgieters',
      address: 'Waterweg 5',
      postalCode: '1018 AL',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@visser.example',
      contactPersonName: 'Wim Visser'
    },
    {
      companyName: 'Kok Verwarming',
      address: 'Warmtestraat 8',
      postalCode: '1019 AM',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@kok.example',
      contactPersonName: 'Gerda Kok'
    },
    {
      companyName: 'Meijer Dakbedekking',
      address: 'Daklaan 13',
      postalCode: '1020 AN',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@meijer.example',
      contactPersonName: 'Rob Meijer'
    },
    {
      companyName: 'Hendriks Schilders',
      address: 'Verfstraat 17',
      postalCode: '1021 AP',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@hendriks.example',
      contactPersonName: 'Anja Hendriks'
    },
    {
      companyName: 'Van Leeuwen Timmerwerk',
      address: 'Houtlaan 21',
      postalCode: '1022 AQ',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@vanleeuwen.example',
      contactPersonName: 'Dirk van Leeuwen'
    },
    {
      companyName: 'De Boer Metselwerk',
      address: 'Steenweg 24',
      postalCode: '1023 AR',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@deboer.example',
      contactPersonName: 'Niels de Boer'
    },
    {
      companyName: 'Vos Beton',
      address: 'Betonstraat 27',
      postalCode: '1024 AS',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@vos.example',
      contactPersonName: 'Sanne Vos'
    },
    {
      companyName: 'Peters Stucwerk',
      address: 'Pleisterlaan 30',
      postalCode: '1025 AT',
      city: 'Amsterdam',
      country: 'NL',
      email: 'info@peters.example',
      contactPersonName: 'Bart Peters'
    }
  ],
  numberPrefixes: [
    {
      name: '2026-',
      template: '2026-'
    }
  ],
  invoices: [
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 2799,
      status: 'paid',
      number: 1,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 22306,
      status: 'open',
      number: 2,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 7106,
      status: 'canceled',
      number: 3,
      numberPrefix: '2026-',
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 29672,
      status: 'canceled',
      number: 4,
      numberPrefix: '2026-',
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 30335,
      status: 'canceled',
      number: 5,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 6,
      amountCents: 8828,
      status: 'paid',
      number: 6,
      numberPrefix: '2026-',
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 9704,
      status: 'paid',
      number: 7,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 12070,
      status: 'paid',
      number: 8,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 21431,
      status: 'paid',
      number: 9,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 40917,
      status: 'paid',
      number: 10,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 6,
      amountCents: 1718,
      status: 'paid',
      number: 11,
      numberPrefix: '2026-',
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 19342,
      status: 'paid',
      number: 12,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 5,
      amountCents: 2928,
      status: 'canceled',
      number: 13,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 1091,
      status: 'paid',
      number: 14,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 5421,
      status: 'canceled',
      number: 15,
      numberPrefix: '2026-',
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 1507,
      status: 'paid',
      number: 16,
      numberPrefix: '2026-',
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 70986,
      status: 'paid',
      number: 17,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 37458,
      status: 'paid',
      number: 18,
      numberPrefix: '2026-',
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 1236,
      status: 'paid',
      number: 19,
      numberPrefix: '2026-',
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 4,
      amountCents: 561,
      status: 'paid',
      number: 20,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 11749,
      status: 'paid',
      number: 21,
      numberPrefix: '2026-',
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 16340,
      status: 'paid',
      number: 22,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 168531,
      status: 'paid',
      number: 23,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 10,
      amountCents: 111612,
      status: 'canceled',
      number: 24,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 781,
      status: 'paid',
      number: 25,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 11722,
      status: 'paid',
      number: 26,
      numberPrefix: '2026-',
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 1946,
      status: 'canceled',
      number: 27,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 110751,
      status: 'canceled',
      number: 28,
      numberPrefix: '2026-',
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 7,
      amountCents: 1930,
      status: 'paid',
      number: 29,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 20104,
      status: 'paid',
      number: 30,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 3469,
      status: 'paid',
      number: 31,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 3448,
      status: 'paid',
      number: 32,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 30122,
      status: 'paid',
      number: 33,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 8251,
      status: 'canceled',
      number: 34,
      numberPrefix: '2026-',
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 3829,
      status: 'paid',
      number: 35,
      numberPrefix: '2026-',
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 2,
      amountCents: 15483,
      status: 'canceled',
      number: 36,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 5,
      amountCents: 5915,
      status: 'paid',
      number: 37,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 6,
      amountCents: 18320,
      status: 'paid',
      number: 38,
      numberPrefix: '2026-',
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 1031,
      status: 'paid',
      number: 39,
      numberPrefix: '2026-',
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 4103,
      status: 'canceled',
      number: 40,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 13425,
      status: 'paid',
      number: 41,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 7,
      amountCents: 41470,
      status: 'paid',
      number: 42,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 5208,
      status: 'canceled',
      number: 43,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 24296,
      status: 'canceled',
      number: 44,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 1735,
      status: 'paid',
      number: 45,
      numberPrefix: '2026-',
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 3544,
      status: 'canceled',
      number: 46,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 1298,
      status: 'canceled',
      number: 47,
      numberPrefix: '2026-',
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 6,
      amountCents: 6490,
      status: 'open',
      number: 48,
      numberPrefix: '2026-',
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 135527,
      status: 'canceled',
      number: 49,
      numberPrefix: '2026-',
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 2347,
      status: 'canceled',
      number: 50,
      numberPrefix: '2026-',
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 15492,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 23892,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 12,
      amountCents: 38732,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 585,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 2114,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 18498,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 2,
      amountCents: 6794,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 1641,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 9182,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 4711,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 1,
      amountCents: 36949,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 8,
      amountCents: 15970,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 46154,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 2,
      amountCents: 1651,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 11137,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 5,
      amountCents: 546,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 8,
      amountCents: 22591,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 8,
      amountCents: 355,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 4,
      amountCents: 43425,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 10,
      amountCents: 14027,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 98480,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 11944,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 4,
      amountCents: 1164,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 66122,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 11,
      amountCents: 8684,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 15540,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 6260,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 2306,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 11,
      amountCents: 17801,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 3,
      amountCents: 52004,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 8,
      amountCents: 9137,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 5120,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 23617,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 29492,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 10,
      amountCents: 3772,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 1474,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 8436,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 6,
      amountCents: 17866,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 26857,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 3,
      amountCents: 384,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 16546,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 9763,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 10,
      amountCents: 2741,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 0,
      amountCents: 2501,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 3105,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 7,
      amountCents: 1928,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 6473,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 9,
      amountCents: 47571,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 32667,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 2,
      amountCents: 6738,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 2,
      amountCents: 81726,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 10,
      amountCents: 171218,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 2272,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 2685,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 6,
      amountCents: 7697,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 7,
      amountCents: 15913,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 45441,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 5,
      amountCents: 56937,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 8125,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 0,
      amountCents: 5186,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 10,
      amountCents: 9243,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 310,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 13,
      amountCents: 17123,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 3,
      amountCents: 124777,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 8,
      amountCents: 25827,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 13,
      amountCents: 13591,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 7,
      amountCents: 2960,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 8934,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 9,
      amountCents: 13778,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 9,
      amountCents: 56383,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 2,
      amountCents: 1691,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 1986,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 8494,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 3217,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 1,
      amountCents: 542,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 7,
      amountCents: 2105,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 7,
      amountCents: 49865,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 5276,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 5,
      amountCents: 40344,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 35450,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 997,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 2,
      amountCents: 1803,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 13181,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 4,
      amountCents: 2626,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 37512,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 33644,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 12,
      amountCents: 1927,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 9,
      amountCents: 3275,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 2,
      amountCents: 14152,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 11837,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 8,
      amountCents: 6683,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 6231,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 4,
      amountCents: 200000,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 7,
      amountCents: 13596,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 6,
      amountCents: 3598,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 5,
      amountCents: 3360,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 7,
      amountCents: 1166,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 10,
      amountCents: 16851,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 0,
      amountCents: 16410,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 6617,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 3,
      amountCents: 14867,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 2893,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 0,
      amountCents: 7294,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 6,
      amountCents: 588,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 11,
      amountCents: 13132,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 4,
      amountCents: 649,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 10,
      amountCents: 22693,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 5,
      amountCents: 24448,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 1849,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 5,
      amountCents: 10606,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 10522,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 4,
      amountCents: 64669,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 22362,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 12792,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 4,
      amountCents: 16486,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 4,
      amountCents: 3227,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 11,
      amountCents: 12251,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 4,
      amountCents: 15831,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 9,
      amountCents: 5152,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 2,
      amountCents: 15956,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 1804,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 9,
      amountCents: 11392,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 11,
      amountCents: 22594,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 3,
      amountCents: 4206,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 4,
      amountCents: 11078,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Consultancy services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 13,
      amountCents: 22698,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 63440,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 4,
      amountCents: 14583,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 2,
      amountCents: 11443,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 11,
      amountCents: 7806,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Transport and logistics',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 6,
      amountCents: 3262,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 970,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 2097,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 43975,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 8,
      amountCents: 7342,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 1,
      amountCents: 2791,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 5,
      amountCents: 21194,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 6913,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 10,
      amountCents: 14627,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 9,
      amountCents: 76829,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 8,
      amountCents: 15858,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Maintenance contract',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 9,
      amountCents: 7821,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 1,
      amountCents: 28278,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 1,
      clientIndex: 12,
      amountCents: 100360,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Materials and supplies',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 3674,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Design services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 13,
      amountCents: 36959,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Software license',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 12,
      amountCents: 15285,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Training session',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 0,
      clientIndex: 1,
      amountCents: 13584,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Repair work',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 6,
      amountCents: 3402,
      status: 'receipt',
      number: null,
      numberPrefix: null,
      lineDescription: 'Cleaning services',
      paymentTermDays: 14,
      locale: 'en-US'
    },
    {
      companyIndex: 2,
      clientIndex: 3,
      amountCents: 33291,
      status: 'bill',
      number: null,
      numberPrefix: null,
      lineDescription: 'Installation work',
      paymentTermDays: 14,
      locale: 'en-US'
    }
  ],
  payments: [
    {
      invoiceIndex: 0,
      amountCents: 1976,
      method: 'ideal',
      externalId: 'tr-zwhh62m6du',
      settlementId: 'stl-do6eiwoj0l',
      description: 'Mollie payout 1'
    },
    {
      invoiceIndex: 5,
      amountCents: 7601,
      method: 'ideal',
      externalId: 'tr-9wc7eocb4u',
      settlementId: 'stl-6tm9bw26v5',
      description: 'Mollie payout 6'
    },
    {
      invoiceIndex: 6,
      amountCents: 6540,
      method: 'ideal',
      externalId: 'tr-u8esue5akv',
      settlementId: 'stl-4hhfo5adot',
      description: 'Mollie payout 7'
    },
    {
      invoiceIndex: 7,
      amountCents: 6660,
      method: 'ideal',
      externalId: 'tr-5e0s5jdbvp',
      settlementId: 'stl-2kfq5cxq04',
      description: 'Mollie payout 8'
    },
    {
      invoiceIndex: 8,
      amountCents: 19231,
      method: 'ideal',
      externalId: 'tr-z5v6oba4xq',
      settlementId: 'stl-2kfq5cxq04',
      description: 'Mollie payout 9'
    },
    {
      invoiceIndex: 9,
      amountCents: 35308,
      method: 'ideal',
      externalId: 'tr-20m5pnebuh',
      settlementId: 'stl-2kfq5cxq04',
      description: 'Mollie payout 10'
    },
    {
      invoiceIndex: 10,
      amountCents: 464,
      method: 'ideal',
      externalId: 'tr-ygoodwmgag',
      settlementId: 'stl-37z3v6a32b',
      description: 'Mollie payout 11'
    },
    {
      invoiceIndex: 11,
      amountCents: 6643,
      method: 'creditcard',
      externalId: 'tr-4r4hbe51rz',
      settlementId: 'stl-37z3v6a32b',
      description: 'Mollie payout 12'
    },
    {
      invoiceIndex: 13,
      amountCents: 1056,
      method: 'ideal',
      externalId: 'tr-g7myaxtfc1',
      settlementId: 'stl-37z3v6a32b',
      description: 'Mollie payout 14'
    },
    {
      invoiceIndex: 15,
      amountCents: 886,
      method: 'ideal',
      externalId: 'tr-fsbqo1y8yf',
      settlementId: 'stl-ovdsxe3fd9',
      description: 'Mollie payout 16'
    },
    {
      invoiceIndex: 16,
      amountCents: 16182,
      method: 'ideal',
      externalId: 'tr-dcvdil5t7e',
      settlementId: 'stl-045w5mfj17',
      description: 'Mollie payout 17'
    },
    {
      invoiceIndex: 17,
      amountCents: 20842,
      method: 'ideal',
      externalId: 'tr-sfj3wapip1',
      settlementId: 'stl-ck9819yiop',
      description: 'Mollie payout 18'
    },
    {
      invoiceIndex: 18,
      amountCents: 706,
      method: 'ideal',
      externalId: 'tr-55sn0qtnjx',
      settlementId: 'stl-ck9819yiop',
      description: 'Mollie payout 19'
    },
    {
      invoiceIndex: 19,
      amountCents: 470,
      method: 'creditcard',
      externalId: 'tr-ly50vmg0hn',
      settlementId: 'stl-ck9819yiop',
      description: 'Mollie payout 20'
    },
    {
      invoiceIndex: 20,
      amountCents: 10657,
      method: 'ideal',
      externalId: 'tr-4wma700wna',
      settlementId: 'stl-pd7ka8vje1',
      description: 'Mollie payout 21'
    },
    {
      invoiceIndex: 21,
      amountCents: 9159,
      method: 'ideal',
      externalId: 'tr-4s5qt1h029',
      settlementId: 'stl-pd7ka8vje1',
      description: 'Mollie payout 22'
    },
    {
      invoiceIndex: 22,
      amountCents: 86442,
      method: 'ideal',
      externalId: 'tr-olhuucijzu',
      settlementId: 'stl-s5viuczb64',
      description: 'Mollie payout 23'
    },
    {
      invoiceIndex: 24,
      amountCents: 229,
      method: 'ideal',
      externalId: 'tr-sicmyogepu',
      settlementId: 'stl-s5viuczb64',
      description: 'Mollie payout 25'
    },
    {
      invoiceIndex: 25,
      amountCents: 10925,
      method: 'ideal',
      externalId: 'tr-hjraq2ej9k',
      settlementId: 'stl-s5viuczb64',
      description: 'Mollie payout 26'
    },
    {
      invoiceIndex: 28,
      amountCents: 1878,
      method: 'ideal',
      externalId: 'tr-rjsrcw4u8l',
      settlementId: 'stl-ex84gsz5rm',
      description: 'Mollie payout 29'
    },
    {
      invoiceIndex: 29,
      amountCents: 17639,
      method: 'ideal',
      externalId: 'tr-q5oovewyg7',
      settlementId: 'stl-ex84gsz5rm',
      description: 'Mollie payout 30'
    },
    {
      invoiceIndex: 30,
      amountCents: 727,
      method: 'ideal',
      externalId: 'tr-7j7dmslxp1',
      settlementId: 'stl-ex84gsz5rm',
      description: 'Mollie payout 31'
    },
    {
      invoiceIndex: 31,
      amountCents: 3109,
      method: 'ideal',
      externalId: 'tr-c36lah7pgw',
      settlementId: 'stl-64cvxmujt5',
      description: 'Mollie payout 32'
    },
    {
      invoiceIndex: 32,
      amountCents: 14171,
      method: 'ideal',
      externalId: 'tr-au268j9en7',
      settlementId: 'stl-hkifs7cpqc',
      description: 'Mollie payout 33'
    },
    {
      invoiceIndex: 34,
      amountCents: 3735,
      method: 'ideal',
      externalId: 'tr-607yjg8fqy',
      settlementId: 'stl-hkifs7cpqc',
      description: 'Mollie payout 35'
    },
    {
      invoiceIndex: 36,
      amountCents: 5365,
      method: 'ideal',
      externalId: 'tr-erfu17dewz',
      settlementId: 'stl-iafa6vf7ti',
      description: 'Mollie payout 37'
    },
    {
      invoiceIndex: 37,
      amountCents: 6541,
      method: 'ideal',
      externalId: 'tr-h0b957lozp',
      settlementId: 'stl-iafa6vf7ti',
      description: 'Mollie payout 38'
    },
    {
      invoiceIndex: 38,
      amountCents: 323,
      method: 'ideal',
      externalId: 'tr-198dlgbilw',
      settlementId: 'stl-3toasmvpth',
      description: 'Mollie payout 39'
    },
    {
      invoiceIndex: 40,
      amountCents: 10648,
      method: 'ideal',
      externalId: 'tr-mkexd3lpr8',
      settlementId: 'stl-3toasmvpth',
      description: 'Mollie payout 41'
    },
    {
      invoiceIndex: 41,
      amountCents: 33489,
      method: 'ideal',
      externalId: 'tr-uu9ef8xxaq',
      settlementId: 'stl-3toasmvpth',
      description: 'Mollie payout 42'
    },
    {
      invoiceIndex: 44,
      amountCents: 1177,
      method: 'ideal',
      externalId: 'tr-eropldq7m5',
      settlementId: 'stl-n3tlgfynp5',
      description: 'Mollie payout 45'
    },
    {
      invoiceIndex: 0,
      amountCents: 1155,
      method: 'ideal',
      externalId: 'tr-fq6iybljn1',
      settlementId: 'stl-n3tlgfynp5',
      description: 'Mollie payout 1'
    },
    {
      invoiceIndex: 5,
      amountCents: 7828,
      method: 'ideal',
      externalId: 'tr-rrt2mtfhjt',
      settlementId: 'stl-n3tlgfynp5',
      description: 'Mollie payout 6'
    },
    {
      invoiceIndex: 6,
      amountCents: 8012,
      method: 'ideal',
      externalId: 'tr-r5hd9qwuis',
      settlementId: 'stl-zx0qjt2sdw',
      description: 'Mollie payout 7'
    },
    {
      invoiceIndex: 7,
      amountCents: 6509,
      method: 'creditcard',
      externalId: 'tr-2orl2n3ty0',
      settlementId: 'stl-zx0qjt2sdw',
      description: 'Mollie payout 8'
    },
    {
      invoiceIndex: 8,
      amountCents: 6905,
      method: 'ideal',
      externalId: 'tr-mzldr39wxg',
      settlementId: 'stl-zx0qjt2sdw',
      description: 'Mollie payout 9'
    },
    {
      invoiceIndex: 9,
      amountCents: 18879,
      method: 'ideal',
      externalId: 'tr-ygolubhw0j',
      settlementId: 'stl-lb8ek0pmjh',
      description: 'Mollie payout 10'
    },
    {
      invoiceIndex: 10,
      amountCents: 656,
      method: 'ideal',
      externalId: 'tr-5k5l6uzxsu',
      settlementId: 'stl-lb8ek0pmjh',
      description: 'Mollie payout 11'
    },
    {
      invoiceIndex: 11,
      amountCents: 14628,
      method: 'ideal',
      externalId: 'tr-xd83dctce9',
      settlementId: 'stl-lb8ek0pmjh',
      description: 'Mollie payout 12'
    },
    {
      invoiceIndex: 13,
      amountCents: 697,
      method: 'ideal',
      externalId: 'tr-xq0pe8w86l',
      settlementId: 'stl-yj21u8kgvu',
      description: 'Mollie payout 14'
    },
    {
      invoiceIndex: 15,
      amountCents: 767,
      method: 'ideal',
      externalId: 'tr-m0desevuua',
      settlementId: 'stl-yj21u8kgvu',
      description: 'Mollie payout 16'
    },
    {
      invoiceIndex: 16,
      amountCents: 55264,
      method: 'ideal',
      externalId: 'tr-8c7e9tf6v4',
      settlementId: 'stl-yj21u8kgvu',
      description: 'Mollie payout 17'
    },
    {
      invoiceIndex: 17,
      amountCents: 22576,
      method: 'ideal',
      externalId: 'tr-590zyr90y3',
      settlementId: 'stl-t5n4e90g1j',
      description: 'Mollie payout 18'
    },
    {
      invoiceIndex: 18,
      amountCents: 501,
      method: 'ideal',
      externalId: 'tr-adfgljvtqu',
      settlementId: 'stl-wrvvsbfoaw',
      description: 'Mollie payout 19'
    },
    {
      invoiceIndex: 19,
      amountCents: 227,
      method: 'ideal',
      externalId: 'tr-g5leklthww',
      settlementId: 'stl-p8i1m9dtgb',
      description: 'Mollie payout 20'
    },
    {
      invoiceIndex: 20,
      amountCents: 4435,
      method: 'ideal',
      externalId: 'tr-6v7mgfoqhv',
      settlementId: 'stl-nr3ixm41yu',
      description: 'Mollie payout 21'
    },
    {
      invoiceIndex: 21,
      amountCents: 5280,
      method: 'ideal',
      externalId: 'tr-326bx9his4',
      settlementId: 'stl-a52d0mdgl4',
      description: 'Mollie payout 22'
    },
    {
      invoiceIndex: 22,
      amountCents: 91471,
      method: 'ideal',
      externalId: 'tr-y5r1irgszy',
      settlementId: 'stl-ezm3yj5ea6',
      description: 'Mollie payout 23'
    },
    {
      invoiceIndex: 24,
      amountCents: 774,
      method: 'ideal',
      externalId: 'tr-ymo4w41lfj',
      settlementId: 'stl-ezm3yj5ea6',
      description: 'Mollie payout 25'
    },
    {
      invoiceIndex: 25,
      amountCents: 3497,
      method: 'ideal',
      externalId: 'tr-e8rwc4zsq6',
      settlementId: 'stl-sj2ohb1ely',
      description: 'Mollie payout 26'
    },
    {
      invoiceIndex: 28,
      amountCents: 1503,
      method: 'ideal',
      externalId: 'tr-8k6fc7qqnl',
      settlementId: 'stl-sj2ohb1ely',
      description: 'Mollie payout 29'
    },
    {
      invoiceIndex: 29,
      amountCents: 17363,
      method: 'ideal',
      externalId: 'tr-zihen6vyvn',
      settlementId: 'stl-sj2ohb1ely',
      description: 'Mollie payout 30'
    },
    {
      invoiceIndex: 30,
      amountCents: 833,
      method: 'ideal',
      externalId: 'tr-o2o61v4s2h',
      settlementId: 'stl-fo9b68ft2r',
      description: 'Mollie payout 31'
    },
    {
      invoiceIndex: 31,
      amountCents: 2370,
      method: 'ideal',
      externalId: 'tr-1swl5tmlfm',
      settlementId: 'stl-gwhz7xcnbx',
      description: 'Mollie payout 32'
    },
    {
      invoiceIndex: 32,
      amountCents: 22114,
      method: 'ideal',
      externalId: 'tr-a4rt1ahg4y',
      settlementId: 'stl-gwhz7xcnbx',
      description: 'Mollie payout 33'
    },
    {
      invoiceIndex: 34,
      amountCents: 2434,
      method: 'ideal',
      externalId: 'tr-fx4ljakgci',
      settlementId: 'stl-gwhz7xcnbx',
      description: 'Mollie payout 35'
    },
    {
      invoiceIndex: 36,
      amountCents: 3883,
      method: 'ideal',
      externalId: 'tr-n8pg27ojb8',
      settlementId: 'stl-wiu2kcsl12',
      description: 'Mollie payout 37'
    },
    {
      invoiceIndex: 37,
      amountCents: 4824,
      method: 'ideal',
      externalId: 'tr-xos9e1fz4d',
      settlementId: 'stl-wiu2kcsl12',
      description: 'Mollie payout 38'
    },
    {
      invoiceIndex: 38,
      amountCents: 408,
      method: 'ideal',
      externalId: 'tr-u2pdoo0irh',
      settlementId: 'stl-1xfbbvcec2',
      description: 'Mollie payout 39'
    },
    {
      invoiceIndex: 40,
      amountCents: 12072,
      method: 'ideal',
      externalId: 'tr-4i3fpmde0i',
      settlementId: 'stl-1xfbbvcec2',
      description: 'Mollie payout 41'
    },
    {
      invoiceIndex: 41,
      amountCents: 13905,
      method: 'ideal',
      externalId: 'tr-r7per97ynm',
      settlementId: 'stl-1xfbbvcec2',
      description: 'Mollie payout 42'
    },
    {
      invoiceIndex: 50,
      amountCents: 15492,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 55,
      amountCents: 18498,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 56,
      amountCents: 6794,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 58,
      amountCents: 9182,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 60,
      amountCents: 36949,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 61,
      amountCents: 15970,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 62,
      amountCents: 46154,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 68,
      amountCents: 43425,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 69,
      amountCents: 14027,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 70,
      amountCents: 98480,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 74,
      amountCents: 8684,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 77,
      amountCents: 2306,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 78,
      amountCents: 17801,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 79,
      amountCents: 52004,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 80,
      amountCents: 9137,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 83,
      amountCents: 29492,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 84,
      amountCents: 3772,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 87,
      amountCents: 17866,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 92,
      amountCents: 2741,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 93,
      amountCents: 2501,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 94,
      amountCents: 3105,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 95,
      amountCents: 1928,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 97,
      amountCents: 47571,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 98,
      amountCents: 32667,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 100,
      amountCents: 81726,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 101,
      amountCents: 171218,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 102,
      amountCents: 2272,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 104,
      amountCents: 7697,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 105,
      amountCents: 15913,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 106,
      amountCents: 45441,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 108,
      amountCents: 8125,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 114,
      amountCents: 25827,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 116,
      amountCents: 2960,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 121,
      amountCents: 1986,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 124,
      amountCents: 542,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 125,
      amountCents: 2105,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 126,
      amountCents: 49865,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 129,
      amountCents: 35450,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 131,
      amountCents: 1803,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 132,
      amountCents: 13181,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 135,
      amountCents: 33644,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 138,
      amountCents: 14152,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 139,
      amountCents: 11837,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 143,
      amountCents: 13596,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 148,
      amountCents: 16410,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 150,
      amountCents: 14867,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 151,
      amountCents: 2893,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 155,
      amountCents: 649,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 157,
      amountCents: 24448,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 160,
      amountCents: 10522,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 164,
      amountCents: 16486,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 167,
      amountCents: 15831,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 174,
      amountCents: 11078,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 175,
      amountCents: 22698,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 180,
      amountCents: 3262,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 181,
      amountCents: 970,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 182,
      amountCents: 2097,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 183,
      amountCents: 43975,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 189,
      amountCents: 76829,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 191,
      amountCents: 7821,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 196,
      amountCents: 15285,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 197,
      amountCents: 13584,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    },
    {
      invoiceIndex: 198,
      amountCents: 3402,
      method: 'banktransfer',
      externalId: null,
      settlementId: null,
      description: 'Bank transfer'
    }
  ],
  refunds: [
    {
      paymentExternalId: 'tr-g7myaxtfc1',
      amountCents: 727,
      externalId: 're-7di5g5htby',
      description: 'Refund'
    },
    {
      paymentExternalId: 'tr-590zyr90y3',
      amountCents: 17914,
      externalId: 're-fpvr2qw2s5',
      description: 'Refund'
    }
  ]
} as const
