/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparisonCard: typeof import('./src/components/ComparisonCard.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QCarousel: typeof import('quasar')['QCarousel']
    QCarouselSlide: typeof import('quasar')['QCarouselSlide']
    QDrawer: typeof import('quasar')['QDrawer']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QImg: typeof import('quasar')['QImg']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QNoSsr: typeof import('quasar')['QNoSsr']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QRouteTab: typeof import('quasar')['QRouteTab']
    QSpace: typeof import('quasar')['QSpace']
    QTabs: typeof import('quasar')['QTabs']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
