import { db } from '../index.js'
import type { Insertable } from 'kysely'
import type { Companies, Clients, NumberPrefixes } from '../types.js'
import {
  createBankTransferPaymentHandler,
  createInvoiceHandler,
  InvoiceStatus,
  PaymentMethod,
  PaymentStatus,
  RefundStatus
} from '@modular-api/fastify-checkout'
import { fastify as createFastify } from 'fastify'
import { pathToFileURL } from 'url'
import { demoCore } from '@slimfact/tools/banking/demo/core'

// Fixture-driven demo seed. Replaces the old faker-based generator: it replays
// the committed `demoCore` fixture (owned by @slimfact/tools/banking/demo,
// generated by packages/tools/scripts/generate-demo-data.mjs) through the real
// app flow — createInvoice →
// openInvoice → addPaymentToInvoice → setInvoiceStatus — so immutability,
// numbering and the company/client snapshots come from the real code path.
//
// Numbered invoices (OPEN/PAID/CANCELED, prefix 2026-) go through openInvoice
// and get the fixture's numbers. Unnumbered BILL/RECEIPT documents stay
// unnumbered. PSP-linked payments (ideal/creditcard with a settlementId) are
// raw-inserted into checkout.payments (addPaymentToInvoice has no
// externalId/settlementId seam); bank-transfer payments for receipts go
// through addPaymentToInvoice.

const fastify = createFastify()
const invoiceHandler = createInvoiceHandler({
  fastify,
  kysely: db,
  paymentHandlers: {
    bankTransfer: createBankTransferPaymentHandler({ fastify, kysely: db })
  }
})

export const seedDemo = async (): Promise<void> => {
  const { companies, clients, numberPrefixes, invoices, payments, refunds } =
    demoCore

  // Re-seed guard: early-exit if the demo world already exists, so re-running
  // never shifts the numbers. Key it on the demo's OWN company prefixes — NOT on
  // an invoice number prefix, because seed:test uses '2026-' too and the test
  // stack runs seed:test immediately before seed:demo (`migrate && seed:test &&
  // seed:demo && start`). Keying on the shared prefix made this guard fire
  // whenever seed:test had run, silently skipping the entire demo dataset —
  // which left the dashboard year view with revenue in one quarter only.
  const demoCompanyPrefixes = companies.map((company) => company.prefix)
  const existing = await db
    .selectFrom('companies')
    .select('id')
    .where('prefix', 'in', demoCompanyPrefixes)
    .limit(1)
    .executeTakeFirst()
  if (existing) {
    console.log('[seed:demo] demo data already present, skipping')
    return
  }

  // SAFETY: demoCore is JSON.stringify'd from synth's `as const` output, so each
  // collection is a readonly tuple of literal types while Insertable<> expects
  // mutable arrays. The shapes are the generator's own seed rows, verified
  // end-to-end by demo-seed.spec + demo-fixture-coherence.spec.
  const numberPrefixRows =
    numberPrefixes as unknown as Insertable<NumberPrefixes>[]
  // SAFETY: as above — readonly literal tuple vs Insertable<>'s mutable shape.
  const companyRows = companies as unknown as Insertable<Companies>[]
  // SAFETY: as above — readonly literal tuple vs Insertable<>'s mutable shape.
  const clientRows = clients as unknown as Insertable<Clients>[]

  await db.insertInto('numberPrefixes').values(numberPrefixRows).execute()
  await db.insertInto('companies').values(companyRows).execute()
  await db.insertInto('clients').values(clientRows).execute()

  const insertedCompanies = await db
    .selectFrom('companies')
    .selectAll()
    .execute()
  const insertedClients = await db.selectFrom('clients').selectAll().execute()

  await db
    .insertInto('initialNumberForPrefixes')
    .values({
      companyId: insertedCompanies[0].id,
      numberPrefix: '2026-',
      initialNumber: 1
    })
    .onConflict((oc) => oc.doNothing())
    .execute()

  const { initialNumber } =
    (await db
      .selectFrom('initialNumberForPrefixes')
      .where('numberPrefix', '=', '2026-')
      .select('initialNumber')
      .executeTakeFirst()) || {}

  // Create invoices in fixture order (numbered first, then unnumbered).
  // Each invoice gets a deterministic creation date staggered ~30 days apart
  // so the dashboard revenue chart has bars in every quarter of the year and
  // the activity feed spreads across periods.
  const DAY_MS = 24 * 60 * 60 * 1000
  // Spread across ~400 days so the current year has revenue in every quarter.
  const SPAN_DAYS = 400
  const STEP_MS = (SPAN_DAYS / invoices.length) * DAY_MS
  const invoiceDates = new Map<number, string>(
    invoices.map((_, i) => [
      i,
      new Date(Date.now() - (invoices.length - i) * STEP_MS).toISOString()
    ])
  )
  const createdIds = new Map<number, number>()
  for (let i = 0; i < invoices.length; i++) {
    const inv = invoices[i]
    const company = insertedCompanies[inv.companyIndex]
    const client = insertedClients[inv.clientIndex]
    const isNumbered = inv.number !== null
    const created = await invoiceHandler.createInvoice({
      companyDetails: company,
      clientDetails: client,
      companyPrefix: company.prefix,
      numberPrefixTemplate: '2026-',
      currency: 'EUR',
      lines: [
        {
          description: inv.lineDescription,
          listPrice: inv.amountCents,
          listPriceIncludesTax: true,
          taxRate: 0,
          quantity: 1,
          quantityPerMille: false,
          discount: 0
        }
      ],
      discounts: [],
      surcharges: [],
      paymentTermDays: inv.paymentTermDays,
      locale: inv.locale,
      status: isNumbered ? InvoiceStatus.CONCEPT : InvoiceStatus.BILL,
      companyId: company.id,
      clientId: client.id
    })
    if (!created.success) throw new Error(created.errorMessage)
    createdIds.set(i, created.invoice.id)

    if (isNumbered) {
      const opened = await invoiceHandler.openInvoice({
        id: created.invoice.id,
        numberPrefix: '2026-',
        initialNumber
      })
      if (!opened.success) throw new Error(opened.errorMessage)
      if (inv.status === 'canceled') {
        // cancelInvoice (not setInvoiceStatus) — an opened invoice can only be
        // canceled via the direct cancel path.
        const canceled = await invoiceHandler.cancelInvoice({
          id: created.invoice.id
        })
        if (!canceled.success) throw new Error(canceled.errorMessage)
      }
    }
  }

  // Backdate created_at AND shift due dates along with it, so the seeded
  // world has overdue invoices across all aging buckets plus upcoming ones
  // — exactly what the dashboard action-items and income cards expect from
  // a long-running business.
  for (const [idx, date] of invoiceDates) {
    const inv = invoices[idx]
    const due = new Date(
      new Date(date).getTime() + inv.paymentTermDays * DAY_MS
    ).toISOString()
    await db
      .updateTable('checkout.invoices')
      .where('id', '=', createdIds.get(idx)!)
      .set({ createdAt: date, dueDate: due })
      .execute()
  }

  // Apply payments. PSP-linked payments are raw-inserted (they carry
  // externalId/settlementId); bank-transfer payments go through the app flow.
  // Two passes: app-flow payments first, raw PSP inserts last. Payment
  // activity sorts by paid_at; numbered-invoice PSP payments must be the
  // NEWEST entries so they land inside the dashboard feed's fetch limit
  // (bill/receipt payments have no document number to show).
  const appFlowPayments = payments.filter(
    (payment) => payment.externalId === null || payment.settlementId === null
  )
  const pspPayments = payments.filter(
    (payment) => payment.externalId !== null && payment.settlementId !== null
  )
  for (const payment of [...appFlowPayments, ...pspPayments]) {
    const invoiceId = createdIds.get(payment.invoiceIndex)!
    const inv = invoices[payment.invoiceIndex]
    if (payment.externalId !== null && payment.settlementId !== null) {
      await db
        .insertInto('checkout.payments')
        .values({
          invoiceId,
          externalId: payment.externalId,
          settlementId: payment.settlementId,
          method: payment.method as PaymentMethod,
          paymentServiceProvider: 'mollie',
          amount: payment.amountCents,
          currency: 'EUR',
          status: PaymentStatus.PAID,
          // A paid PSP payment must carry paidAt — the dashboard activity
          // feed, revenue chart and payments overview all filter on it.
          paidAt: new Date(
            new Date(invoiceDates.get(payment.invoiceIndex)!).getTime() +
              2 * DAY_MS
          ).toISOString(),
          description: payment.description
        })
        .execute()
    } else {
      const paid = await invoiceHandler.addPaymentToInvoice({
        id: invoiceId,
        payment: {
          amount: payment.amountCents,
          currency: 'EUR',
          description: payment.description,
          method: payment.method as PaymentMethod,
          date: invoiceDates.get(payment.invoiceIndex)
        }
      })
      if (!paid.success) throw new Error(paid.errorMessage)
      // A fully paid bill converts to a receipt via setInvoiceStatus (app flow).
      if (inv.status === 'receipt') {
        const receipt = await invoiceHandler.setInvoiceStatus({
          id: invoiceId,
          status: InvoiceStatus.RECEIPT
        })
        if (!receipt.success) throw new Error(receipt.errorMessage)
      }
    }
  }

  // Mark PAID numbered invoices as PAID (their PSP payments are raw-inserted,
  // which does not flip the status).
  for (let i = 0; i < invoices.length; i++) {
    if (invoices[i].status === 'paid') {
      await db
        .updateTable('checkout.invoices')
        .set({ status: InvoiceStatus.PAID })
        .where('id', '=', createdIds.get(i)!)
        .execute()
    }
  }

  // Insert refunds, resolving each refund's payment_id by the PSP externalId.
  for (const refund of refunds) {
    const paymentRow = await db
      .selectFrom('checkout.payments')
      .select('id')
      .where('externalId', '=', refund.paymentExternalId)
      .executeTakeFirst()
    if (!paymentRow) {
      throw new Error(
        `[seed:demo] refund payment not found: ${refund.paymentExternalId}`
      )
    }
    await db
      .insertInto('checkout.refunds')
      .values({
        externalId: refund.externalId,
        paymentId: paymentRow.id,
        description: refund.description,
        paymentServiceProvider: 'mollie',
        amount: refund.amountCents,
        currency: 'EUR',
        status: RefundStatus.REFUNDED
      })
      .execute()
  }

  console.log(
    `[seed:demo] seeded ${invoices.length} invoices, ${payments.length} payments, ${refunds.length} refunds`
  )
}

// CLI entry: run when executed directly (node dist/kysely/seeds/demo.js).
const isMain =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) {
  seedDemo().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
